# Generated by Django 5.1.2 on 2024-11-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='area',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='tour',
            name='bathrooms',
            field=models.IntegerField(null=True, verbose_name='Bathrooms'),
        ),
        migrations.AddField(
            model_name='tour',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='rooms',
            field=models.IntegerField(null=True, verbose_name='Rooms'),
        ),
    ]
